language: php
php:
- 7.1
- 7.0
services:
- redis-server
- memcached
before_script:
- composer self-update
- travis_retry composer install --prefer-dist --no-interaction
- mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
- mkdir -p ~/.okta
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
- travis_retry vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  - TRAVIS_NODE_VERSION="8"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
