language: php

env:
  global:
    - coverage=false
    - setup=basic

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

before_script:
- mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
- mkdir -p ~/.okta

script:
- vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env:
        - coverage=true
        - setup=stable